import type { Metadata } from "next";
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { MainSidebar } from "@/components/general/MainSidebar";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SidebarProvider>
          <MainSidebar />
          <SidebarInset>
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
