services:
  skaff-web:
    build:
      context: ../../..
      dockerfile: apps/web/docker/Dockerfile
    # image: timonteutelink/skaff:latest
    ports:
      - "3000:3000"
    environment:
      PROJECT_SEARCH_PATHS: /skaff/projects
    volumes:
      - ~/Projects/MrBlueStudios/templated:/skaff/projects
    # entrypoint: ["ls", "-la"]
