services:
  skaff-web:
    build:
      context: ../../..
      dockerfile: apps/web/docker/Dockerfile
    image: timonteutelink/skaff:latest
    ports:
      - "3000:3000"
    volumes:
      - ~/projects/templated:/projects
    # entrypoint: ["which", "bun"]
    # entrypoint: ["ls", "-la"]
    # entrypoint: ["ls", "-la", "/app/node_modules/typescript/lib"]
