name: publish

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12
      - run: bun install
      - run: bun run build
      - run: bun run prepack
      - uses: JS-DevTools/npm-publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - run: bun run postpack
