name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21

      - name: Install dependencies
        run: cd packages/docs && bun install --frozen-lockfile --ignore-scripts

      - name: Install types lib dependencies
        run: cd packages/template-types-lib && bun install --frozen-lockfile --ignore-scripts

      - name: Install skaff lib dependencies
        run: cd packages/skaff-lib && bun install --frozen-lockfile --ignore-scripts

      - name: Install cli dependencies
        run: cd apps/cli && bun install --frozen-lockfile --ignore-scripts

      - name: Build website
        run: cd packages/docs && bun run docs

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/docs/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
