name: Release Web

on:
  push:
    tags:
      - 'web-v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure tag on main
        run: |
          if ! git branch -r --contains "$GITHUB_SHA" | grep -q "origin/main"; then
            echo "Tag must reference commit on main branch" >&2
            exit 1
          fi
      - name: Extract version
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/web-v}" >> "$GITHUB_OUTPUT"
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/web
          file: ./apps/web/docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/code-templator-web:${{ steps.vars.outputs.VERSION }}
