name: Test deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12

      - name: Install dependencies
        run: cd packages/docs && bun install --frozen-lockfile --ignore-scripts

      - name: Install types lib dependencies
        run: cd packages/template-types-lib && bun install --frozen-lockfile --ignore-scripts

      - name: Install skaff lib dependencies
        run: cd packages/skaff-lib && bun install --frozen-lockfile --ignore-scripts

      - name: Install cli dependencies
        run: cd apps/cli && bun install --frozen-lockfile --ignore-scripts

      - name: Test build website
        run: cd packages/docs && bun run docs
