name: Test Skaff Lib

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12
      - name: Install dependencies
        run: cd packages/skaff-lib && bun install --frozen-lockfile --ignore-scripts
      - name: Lint
        run: cd packages/skaff-lib && bun run lint
      - name: Test
        run: cd packages/skaff-lib && bun run test
